import type { Metadata } from "next";
import "./globals.css";
import App from "./navbar/page";
import Footer from "./footer/page";
import Cursor from "./components/Cursor";

export const metadata: Metadata = {
  title: "Art by Aradhana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Cursor />
        <App />
        {children}
        <Footer />
      </body>
    </html>
  );
}